# Generated by Django 3.2.8 on 2021-10-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoría', models.CharField(choices=[(1, 'Carnes y embutidos'), (2, 'Frutas y Verduras'), (3, 'Panadería y dulces'), (4, 'Huevos, lacteos y café'), (5, 'Aceites y pastas'), (6, 'Conservas y comida preparada'), (7, 'Zumos y bebidas'), (8, 'Aperitivos'), (9, 'Cosmética y cuidado personal'), (10, 'Hogar y limpieza'), (11, 'Ropa')], default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('etiqueta', models.CharField(blank=True, max_length=30)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
